DOWNSCALE = 1

PLAYER_SIZE = 28 // DOWNSCALE
INTERVAL = 1 / 60.0
PLAYER_SPEED = 1000 // DOWNSCALE
WINDOW_WIDTH = 800 // DOWNSCALE
WINDOW_HEIGHT = 600 // DOWNSCALE
GRID_SIZE = 40 // DOWNSCALE
RENDER_SCALE = DOWNSCALE
