import time
import math
import random

from continuous_maze_env.game.levels.base_level import BaseLevel
from continuous_maze_env.game.utils.constants import PLAYER_SIZE, GRID_SIZE
from continuous_maze_env.game.utils.colors import (
    BLACK,
    GREEN,
    LIGHT_BLUE,
    WHITE,
    BACKGROUND,
    END_ZONE,
)


class LevelTwo(BaseLevel):
    def setup_level(self, random_start: bool = False):
        self.begin_setup()

        self.inner_background.extend(
            [
                self.shapes.Rectangle(
                    x=GRID_SIZE * 0,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 0,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 0,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 0,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 0,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 0,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 0,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 2,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 2,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 2,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 2,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 2,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 2,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 2,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 4,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 1,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 4,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 1,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 5,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 5,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 5,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 5,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 5,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 5,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 5,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 7,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 7,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 7,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 7,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 7,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 7,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 7,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 9,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 9,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 9,
                    y=GRID_SIZE * 13,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 11,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 11,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 11,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 11,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 11,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 11,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 11,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 13,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 13,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 13,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 13,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 13,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 13,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 13,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 15,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 15,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 15,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 15,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 15,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 15,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 15,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 2,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 17,
                    y=GRID_SIZE * 0,
                    width=GRID_SIZE * 3,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 17,
                    y=GRID_SIZE * 2,
                    width=GRID_SIZE * 3,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 17,
                    y=GRID_SIZE * 4,
                    width=GRID_SIZE * 3,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 17,
                    y=GRID_SIZE * 6,
                    width=GRID_SIZE * 3,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 17,
                    y=GRID_SIZE * 8,
                    width=GRID_SIZE * 3,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 17,
                    y=GRID_SIZE * 10,
                    width=GRID_SIZE * 3,
                    height=GRID_SIZE * 2,
                    color=WHITE,
                    batch=self.batch,
                ),
                self.shapes.Rectangle(
                    x=GRID_SIZE * 17,
                    y=GRID_SIZE * 12,
                    width=GRID_SIZE * 3,
                    height=GRID_SIZE * 3,
                    color=WHITE,
                    batch=self.batch,
                ),
            ]
        )

        self.wall_lines.extend(
            [
                # 0
                self.shapes.Line(
                    0, 0, 0, GRID_SIZE * 15, width=4, color=BLACK, batch=self.batch
                ),
                self.shapes.Line(
                    0,
                    GRID_SIZE * 15,
                    GRID_SIZE * 20,
                    GRID_SIZE * 15,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 20,
                    GRID_SIZE * 15,
                    GRID_SIZE * 20,
                    0,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 20, 0, 0, 0, width=4, color=BLACK, batch=self.batch
                ),
                # 1
                self.shapes.Line(
                    GRID_SIZE * 4,
                    GRID_SIZE * 3,
                    GRID_SIZE * 5,
                    GRID_SIZE * 3,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 5,
                    GRID_SIZE * 3,
                    GRID_SIZE * 5,
                    GRID_SIZE * 12,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 5,
                    GRID_SIZE * 12,
                    GRID_SIZE * 4,
                    GRID_SIZE * 12,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 4,
                    GRID_SIZE * 12,
                    GRID_SIZE * 4,
                    GRID_SIZE * 3,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                # 2
                self.shapes.Line(
                    GRID_SIZE * 9,
                    GRID_SIZE * 2,
                    GRID_SIZE * 9,
                    GRID_SIZE * 6,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 9,
                    GRID_SIZE * 6,
                    GRID_SIZE * 11,
                    GRID_SIZE * 6,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 11,
                    GRID_SIZE * 6,
                    GRID_SIZE * 11,
                    GRID_SIZE * 2,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 11,
                    GRID_SIZE * 2,
                    GRID_SIZE * 9,
                    GRID_SIZE * 2,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                # 3
                self.shapes.Line(
                    GRID_SIZE * 9,
                    GRID_SIZE * 13,
                    GRID_SIZE * 9,
                    GRID_SIZE * 9,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 9,
                    GRID_SIZE * 9,
                    GRID_SIZE * 11,
                    GRID_SIZE * 9,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 11,
                    GRID_SIZE * 9,
                    GRID_SIZE * 11,
                    GRID_SIZE * 13,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
                self.shapes.Line(
                    GRID_SIZE * 11,
                    GRID_SIZE * 13,
                    GRID_SIZE * 9,
                    GRID_SIZE * 13,
                    width=4,
                    color=BLACK,
                    batch=self.batch,
                ),
            ]
        )

        # self.wall_lines = [
        #     self.shapes.Line(
        #         0, 0, 0, GRID_SIZE * 15, width=4, color=BLACK, batch=self.batch
        #     ),
        #     self.shapes.Line(
        #         0,
        #         GRID_SIZE * 15,
        #         GRID_SIZE * 20,
        #         GRID_SIZE * 15,
        #         width=4,
        #         color=BLACK,
        #         batch=self.batch,
        #     ),
        #     self.shapes.Line(
        #         GRID_SIZE * 20,
        #         GRID_SIZE * 15,
        #         GRID_SIZE * 20,
        #         0,
        #         width=4,
        #         color=BLACK,
        #         batch=self.batch,
        #     ),
        #     self.shapes.Line(
        #         GRID_SIZE * 20, 0, 0, 0, width=4, color=BLACK, batch=self.batch
        #     ),
        # ]

        self.finish_area = self.shapes.Rectangle(
            x=GRID_SIZE * 13 + 2,
            y=GRID_SIZE * 5 + 2,
            width=GRID_SIZE * 2 - 4,
            height=GRID_SIZE * 2 - 4,
            color=END_ZONE,
            batch=self.batch,
        )

        if random_start:
            self.start_area = self.get_random_start_area()
        else:
            self.start_area = self.shapes.Rectangle(
                x=GRID_SIZE * 11 + 2,
                y=GRID_SIZE * 3 + 2,
                width=GRID_SIZE * 2 - 4,
                height=GRID_SIZE * 2 - 4,
                color=GREEN,
                batch=self.batch,
            )

        self.player_start = (
            self.start_area.x + self.start_area.width / 2 - PLAYER_SIZE / 2,
            self.start_area.y + self.start_area.height / 2 - PLAYER_SIZE / 2,
        )

    def update(self):
        pass
